// <auto-generated />
using System;
using App.DAL.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace App.DAL.EF.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260607120726_FixDateTimeWithTimeZone")]
    partial class FixDateTimeWithTimeZone
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("App.Domain.Chip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DeviceIdentifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeviceIdentifier")
                        .IsUnique();

                    b.ToTable("Chips");
                });

            modelBuilder.Entity("App.Domain.PositionResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Accuracy")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagChipId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("XCoord")
                        .HasColumnType("numeric");

                    b.Property<decimal>("YCoord")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ZCoord")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("TagChipId");

                    b.ToTable("PositionResults");
                });

            modelBuilder.Entity("App.Domain.RawMeasurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnchorChipId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Distance")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Quality")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Rssi")
                        .HasColumnType("numeric");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Snr")
                        .HasColumnType("numeric");

                    b.Property<Guid>("TagChipId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AnchorChipId");

                    b.HasIndex("SessionId");

                    b.HasIndex("TagChipId");

                    b.ToTable("RawMeasurements");
                });

            modelBuilder.Entity("App.Domain.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SessionConfigId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SessionConfigId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("App.Domain.SessionConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PlannedDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SessionConfigs");
                });

            modelBuilder.Entity("App.Domain.SessionConfigChip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChipId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionConfigId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("XCoord")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("YCoord")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ZCoord")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ChipId");

                    b.HasIndex("SessionConfigId", "ChipId")
                        .IsUnique();

                    b.ToTable("SessionConfigChips");
                });

            modelBuilder.Entity("App.Domain.PositionResult", b =>
                {
                    b.HasOne("App.Domain.Session", "Session")
                        .WithMany("PositionResults")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Domain.Chip", "TagChip")
                        .WithMany("PositionResultsAsTag")
                        .HasForeignKey("TagChipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("TagChip");
                });

            modelBuilder.Entity("App.Domain.RawMeasurement", b =>
                {
                    b.HasOne("App.Domain.Chip", "AnchorChip")
                        .WithMany("RawMeasurementsAsAnchor")
                        .HasForeignKey("AnchorChipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("App.Domain.Session", "Session")
                        .WithMany("RawMeasurements")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Domain.Chip", "TagChip")
                        .WithMany("RawMeasurementsAsTag")
                        .HasForeignKey("TagChipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnchorChip");

                    b.Navigation("Session");

                    b.Navigation("TagChip");
                });

            modelBuilder.Entity("App.Domain.Session", b =>
                {
                    b.HasOne("App.Domain.SessionConfig", "SessionConfig")
                        .WithMany("Sessions")
                        .HasForeignKey("SessionConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessionConfig");
                });

            modelBuilder.Entity("App.Domain.SessionConfigChip", b =>
                {
                    b.HasOne("App.Domain.Chip", "Chip")
                        .WithMany("SessionConfigChips")
                        .HasForeignKey("ChipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Domain.SessionConfig", "SessionConfig")
                        .WithMany("SessionConfigChips")
                        .HasForeignKey("SessionConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chip");

                    b.Navigation("SessionConfig");
                });

            modelBuilder.Entity("App.Domain.Chip", b =>
                {
                    b.Navigation("PositionResultsAsTag");

                    b.Navigation("RawMeasurementsAsAnchor");

                    b.Navigation("RawMeasurementsAsTag");

                    b.Navigation("SessionConfigChips");
                });

            modelBuilder.Entity("App.Domain.Session", b =>
                {
                    b.Navigation("PositionResults");

                    b.Navigation("RawMeasurements");
                });

            modelBuilder.Entity("App.Domain.SessionConfig", b =>
                {
                    b.Navigation("SessionConfigChips");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
